name: Run Tests and Upload Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install g++ build-essential libgtest-dev gcovr

      - name: Build and run tests with coverage
        run: |
          mkdir -p build
          g++ --coverage -o build/test_executavel tests/Testes.cpp
          ./build/test_executavel

      - name: Generate code coverage report
        run: |
          gcovr -r . --xml-pretty -o coverage.xml

      - name: Debug coverage file
        run: |
          ls -l coverage.xml
          cat coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          fail_ci_if_error: true
