name: Run Tests

on:
  push:
    branches:
      - main  # Ou qualquer outra branch onde você quer rodar os testes
  pull_request:
    branches:
      - main  # Ou qualquer outra branch onde você quer rodar os testes

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install g++ build-essential libgtest-dev

      - name: Build and run tests
        run: |
          make
          ./build/test_executavel 

