name: Run Tests

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up C++ with GCC
        uses: actions/setup-cpp@v1
        with:
          gcc: '10' 

      - name: Install GoogleTest
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtest-dev cmake
          sudo apt-get install -y build-essential

      - name: Build and run tests
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          ./test_executavel 
