# name: CI with Coverage

# on:
#   push:
#     branches:
#       - main
#   pull_request:

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Check out repository
#       uses: actions/checkout@v3

#     - name: Install Dependencies
#       run: |
#         sudo apt-get update
#         sudo apt-get install g++ build-essential libgtest-dev gcovr
#         sudo apt-get install -y lcov

#     - name: Build Project
#       run: |
#         mkdir -p build
#         make
#         ./build/test_executavel

#     - name: Run Tests with Coverage
#       run: |
#         cd build
#         ctest --output-on-failure
#         lcov --capture --directory . --output-file coverage.info
#         lcov --remove coverage.info '/usr/*' '*/test/*' --output-file coverage.info
#         lcov --list coverage.info

#     - name: Upload Coverage to Codecov
#       uses: codecov/codecov-action@v3
#       with:
#         files: ./build/coverage.info
#         flags: unittests
#         name: codecov-report
#         fail_ci_if_error: true
